driver=org.h2.Driver
url=jdbc:h2:~/aspectow-todos;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=RUNSCRIPT FROM 'classpath:com/aspectran/aspectow/demo/todo/db/todos-schema-h2.sql'
username=sa
password=
